### ISSUE TITLE
Better error handling on the server ip address setting

### ISSUE THREAD

**Issue by madwort** [noiseorchestra/autonomous-noise-unit#12]
If a user accidentally (somehow) enters an invalid and very long ip address, the cursor goes off-screen and it can become fiddly to recover from. Possible fixes include:

* when saving an ip address, do more input verification. Simply truncating the ip4 address to length when saving might be enough to avoid some issues. (e.g. 123.123.123.123.123.123.123.123 -> 123.123.123.123) although obviously more could be done
* adding a "reset config" button to the menu which would reset all settings (including ip address) to defaults - this might do more harm than good (by also resetting e.g. frame size), but might help recover from unexpected problems
* ...something else...

**Comment by madwort** [comment]
was just having a poke around - there's lots of things (e.g. [this](https://docs.python.org/3/library/ipaddress.html) ) that will validate an address & throw an error if it's invalid, but I'm not sure how you could easily deal with that in the UI.

Maybe the best thing would be to adapt [this stackover answer](https://stackoverflow.com/a/319291) to parse the input & convert it to the "nearest" valid ip address - up to four blocks of up to 255 each?

**Comment by sandreae** [comment]
I'm gunna merge https://github.com/noiseorchestra/autonomous-noise-unit/pull/17 which simply protects against very long IP addresses being input (the situation you faced). Obvs much more could be done in terms of validation, but unfortunately, that will have to wait..... I would probably want a little feedback for the user if full IP validation was implemented too.

**Comment by sandreae** [comment]
It was actually a mistake in the conditional logic (:roll_eyes:) where the `==` should have been a `>=` which allowed the condition you found to occur :sob:
