### ISSUE TITLE
Finer control over JackTrip session params in OLED menu

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/autonomous-noise-unit#5]
This will include the ability to change the following params:

- jack pps
- jacktrip hub server IP
- jacktrip queue
- jacktrip channels
- jacktrip peer IP

**Comment by madwort** [comment]
I think that's all we need, but will shout if I think of anything.

**Comment by madwort** [comment]
is this fixed now?

**Comment by sandreae** [comment]
> is this fixed now?

Sorry, what do you mean?

**Comment by madwort** [comment]
ah, I just mean, can this ticket be closed?

**Comment by sandreae** [comment]
Yip 👍👏
